services:
  - type: web
    name: counseling
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "sh start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "True"
