# Generated by Django 5.2.6 on 2026-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0009_grievance_counselor_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounseling',
            name='added_by_role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added by Role'),
        ),
    ]
