# Generated by Django 5.1.5 on 2026-03-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0010_studentcounseling_added_by_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcounseling',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcounseling',
            name='student_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year'),
        ),
    ]
